config/routes.rb
Rails.application.routes.draw do
  # get 'session/new'
  # get 'events/new'
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index]

  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :dropzones
  resources :events
  post '/events/:id/attend' => 'events#attend', :as => 'attend'
  post '/events/:id/unattend' => 'events#unattend', :as => 'unattend'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  has_and_belongs_to_many :events
end

app/models/dropzone.rb
class Dropzone < ApplicationRecord
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :dropzone, :optional => true
  has_and_belongs_to_many :disciplines
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates :license, :length => {maximum: 6}, :allow_blank => true, :uniqueness => true
  has_many :events
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base

    before_action :fetch_user

    private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
      redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
      redirect_to root_path unless @current_user.present? && @current_user.admin?
    end
  end

app/controllers/dropzones_controller.rb
  class DropzonesController < ApplicationController

    def index
      @dropzones = Dropzone.order "created_at desc"
    end

    def show
      @dropzone = Dropzone.find params[:id]
    end

    def new
      @dropzone = Dropzone.new
    end

    def create
      dropzone = Dropzone.create dropzone_params
        if params[:file].present?
          req = Cloudinary::Uploader.upload(params[:file])
          dropzone.image = req["public_id"]
          dropzone.save
        end
      redirect_to dropzone
    end

    def edit
      @dropzone = Dropzone.find params[:id]
    end

    def update
      dropzone = Dropzone.find params[:id]
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        dropzone.image = req["public_id"]
      end
      dropzone.update dropzone_params
      dropzone.save
      redirect_to dropzone_path(dropzone.id)
    end

    def destroy
      dropzone = Dropzone.find params[:id]
      dropzone.destroy
      redirect_to dropzones_path
    end

    private
      def dropzone_params
        params.require(:dropzone).permit(:state, :dz_name, :image, :latitude, :longitude)
      end
  end

app/controllers/events_controller.rb
  class EventsController < ApplicationController

    def index
      @events = Event.order "created_at desc"
    end

    def show
      @event = Event.find params[:id]
    end

    def attend
      event = Event.find params[:id]
      @current_user.events << event
      redirect_to root_path
    end

    def unattend
      event = Event.find params[:id]
      @current_user.events.delete(event)
      redirect_to root_path
    end

    def new
      @event = Event.new
    end

    def create
      event = Event.create event_params
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        event.image = req["public_id"]
        event.save
      end
      redirect_to event
    end

    def edit
      @event = Event.find params[:id]
    end

    def update
      event = Event.find params[:id]
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        event.image = req["public_id"]
      end
      event.update event_params
      event.save
      redirect_to event_path(event.id)
    end

    def destroy
      event = Event.find params[:id]
      event.destroy
      redirect_to events_path
    end

    private
      def event_params
        params.require(:event).permit(:name, :date, :organiser, :coach, :image, :dropzone_id, :price, :contact, :discipline_ids => [])
      end
  end

app/controllers/pages_controller.rb
  class PagesController < ApplicationController
    before_action :check_for_login

    def home
      @user = User.find_by (params[:id])
    end
  end

app/controllers/session_controller.rb
  class SessionController < ApplicationController
    def new
    end

    def create
      user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to root_path
      else
        flash[:error] = "Invalid username or password"
        redirect_to login_path
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to login_path
    end
  end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :check_for_admin, :only => [:index]

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.create user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to :new
      end
    end

    private
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :license)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dropzones_helper.rb
module DropzonesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dropzones/_form.html.erb
<div id = "create_edit">
  <div id="events_create_edit">
    <%= form_for(@dropzone, :html => {:multipart => true}) do |f| %>
      <%= f.label :state %>
      <%= f.text_field :state, :required => true, :autofocus => true %>
      <%= f.label :dz_name %>
      <%= f.text_field :dz_name, :required => true %>
      <%= f.label :image %>
      <%= f.cl_image_upload :image %>
      <%= f.label :latitude %>
      <%= f.number_field :latitude, step: :any %>
      <%= f.label :longitude %>
      <%= f.number_field :longitude, step: :any%>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/dropzones/edit.html.erb
<h1 class="create_edit_heading">Edit <%= @dropzone.dz_name %></h1>

<%= render :partial => 'form' %>

app/views/dropzones/index.html.erb
<div id = "blueskies">

      <% if @current_user.present? %>
        <% if @current_user.admin? %>
            <div class="controls">
              <%= link_to "Create dropzone", new_dropzone_path %>
            </div>
          <% end %>
        <% end %>

    <div id="index">

      <h2>Australian Dropzones</h2>

        <% @dropzones.each do |dropzone| %>
          <p><%= link_to dropzone[:dz_name], dropzone_path(dropzone.id) %></p>
        <% end %>
    </div>
</div>

app/views/dropzones/new.html.erb
<h2 class="create_edit_heading">New Dropzone</h2>

<%= render :partial => 'form' %>

app/views/dropzones/show.html.erb
  <div id = "blueskies">

      <div id="show_html">
        <h2 id="show_html_header"><%= @dropzone[:dz_name] %></h2>

          <% if @dropzone.image.present?  %>
        <div class="img">
          <%= cl_image_tag(@dropzone.image, :crop => :fill, :class => "img") %>
        </div>
        <% end%>

        <% @dropzone.events.each do |event| %>
          <li class="dropzone_events"><%= link_to event.name, event %></li>
        <% end %>

        <% if @current_user.present? %>
        <script>
          $(document).ready(function () {

          const mymap = L.map('mapid').setView([<%= @dropzone.latitude %>, <%= @dropzone.longitude %>], 13);
          L.tileLayer('https://api.maptiler.com/maps/topographique/256/{z}/{x}/{y}.png?key=9IGp47mLypUCXZrtgfzR',{
          attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>'
          }).addTo(mymap);

          L.marker([<%= @dropzone.latitude %>, <%= @dropzone.longitude %>]).addTo(mymap);
        });

          </script>
        </div>

            <% if @current_user.admin? %>
              <div class="controls_show">
              <%= link_to "Edit", edit_dropzone_path(@dropzone.id) %>
              <%= link_to "Delete", @dropzone, :method => 'delete', :data => {:confirm => "Are you sure?"} %>
          </div>
        <% end %>
        <div id="mapid">

        </div>
      <% end %>
    </div>

app/views/events/_form.html.erb
<div id = "create_edit">
  <div id="events_create_edit">
      <%= form_for(@event, :html => {:multipart => true}) do |f|%>
      <%= f.label :name %>
      <%= f.text_field :name, :required => true, :autofocus => true, :placeholder => 'required' %>

    <%= f.label :date %>
    <%= f.date_field :date, :required => true %>

    <%= f.label :organiser %>
    <%= f.text_field :organiser, :required => true, :placeholder => 'required' %>

    <%= f.label :coach %>
    <%= f.text_field :coach %>

    <%= f.label :price %>
    <%= f.number_field :price, :required => true, :placeholder => 'required'%>

    <%= f.label :image %>
    <%= f.cl_image_upload :image %>

    <%= f.label :contact %>
    <%= f.email_field :contact %>

    <%= f.label :dropzone_id %>
    <%= f.select :dropzone_id, Dropzone.pluck(:dz_name, :id), :include_blank =>true %>
    </div>
    <% Discipline.all.each do |discipline| %>
        <%= check_box_tag "event[discipline_ids][]", discipline.id, @event.discipline_ids.include?(discipline.id) %>
        <%= discipline.name %><br/>
      <% end %>

      <%= f.submit %>
    <% end %>
</div>

app/views/events/edit.html.erb
  <h1 class="create_edit_heading">Edit <%= @event.name %></h1>

  <%= render :partial => 'form' %>

app/views/events/index.html.erb
<div id = "blueskies">

      <div class="controls">
        <%= link_to "Create event", new_event_path %>
      </div>

  <div id="index">
    
      <h2> Events </h2>

        <% @events.each do |event| %>
            <p><%= link_to event[:name], event_path(event.id) %></p>
        <% end %>
</div>

app/views/events/new.html.erb
<h1 class="create_edit_heading">New Event</h1>

<%= render :partial => 'form' %>

app/views/events/show.html.erb
<div id = "blueskies">

  <div id="show_html">
    <h2 class="show_event_h2"><%= @event[:name] %></h2>

    <% if @event.image.present?  %>
    <%= cl_image_tag(@event.image, :crop => :fill, :class => "img") %>
    <% end %>

    <ul class="event_details">
      <li>Date: <%= @event[:date].strftime "%e %b %Y"  %></li>
        <% if @event.dropzone.present? %>
          <li>Dropzone: <%= link_to @event.dropzone.dz_name, @event.dropzone %> </li>
        <% end %>
      <li>Organiser: <%= @event[:organiser]%></li>
        <% if @event.coach.present? %>
          <li>Coach: <%= @event[:coach] if @event.coach.present?%></li>
        <% end %>
      <li>Price: <%= number_to_currency @event[:price] if  @event.price.present?%></li>
        <% if @event.contact.present? %>
          <li>Contact: <%= @event[:contact] if @event.contact.present?%></li>
        <% end %>

      <% @event.disciplines.each do |discipline| %>
        <li>Category: <%= discipline.name%></li>
      <% end %>

    </ul>

    <% if @event.user_id == @current_user.id %>
      <%= button_to "Unattend", unattend_path(@event.id)%>
    <% else %>
      <%= button_to "Going", attend_path(@event.id) %>
    <% end %>
  </div>

  <div class="controls_show">
    <%= link_to "Edit", edit_event_path(@event.id) %>
    <%= link_to "Delete", @event, :method => 'delete', :data => {:confirm => "Are you sure?"} %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>
  <div class="container">
    <nav>
          <% if @current_user.present? %>
            <%= link_to "Profile", root_path %>
            <%= link_to "Events", events_path %>
            <%= link_to "Dropzones", dropzones_path %>
            <span class="log_out"><%= link_to "Log out", login_path, :method => 'delete' %></span>
          <% else %>
            <%= link_to 'Sign up', new_user_path %>
            <%= link_to "Login", login_path %>
          <% end %>
    </nav>
   <body>
     <%= yield %>
   </body>
   </div>
</html>

app/views/pages/home.html.erb
    <div id="blueskies">
        <% if @current_user.present? %>

            <% if @current_user.admin? %>
              <div class="controls">
                <%= link_to 'All users', users_path %>
              </div>
            <% end %>
        <div id="profile">
        <% if @current_user.license.present? %>
        <h5 class="license">Licence Number: <br><%= @current_user.license %></h5>
        <% end %>
        <h1><%= @current_user.name %></h1>
        <h2> Your Events </h2>

        <% @current_user.events.each do |event| %>
          <div class="user_list_events"><%= link_to event.name, event %></div>
        <% end %>

       <% end %>
      </div>
    </div>

app/views/session/new.html.erb
<div id = "log_container">
  <div id="log">
    <h1 class="log_heading">Log In</h1>

  <%= flash[:error] %>

    <%= form_tag(login_path, class: "form") do %>
      <%= label_tag :email %>
      <%= email_field_tag :email%>
        <%= label_tag :password %>
      <%= password_field_tag :password%>

      <%= submit_tag "Sign in" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div id="index">
  <h2>List of users</h2>

  <% @users.each do |user| %>
    <p><%= user[:email]%></p>

  <% end %>
</div>

app/views/users/new.html.erb
<div id = "log_container">
<div id ="log">
<h1 class="log_heading">Sign Up</h1>

  <% if @user.errors.any? %>
    <ol>
      <%= @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  <% end %>

  <%= form_for(@user, class:"form") do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :license %>
    <%= f.text_field :license, :placeholder => '#A1234'%>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Sign up!"%>
  <% end %>
  </div>
</div>